### ISSUE TITLE
Proxmox prepare step ansible role missing

### ISSUE THREAD

**Issue by mannp** [sergelogvinov/terraform-talos#4]
ansible-role-users appears to be missing from your repos in order to complete the prepare step for proxmox.

I have continued as its stated as optional.

Cheers

`ansible-galaxy role install git+https://github.com/sergelogvinov/ansible-role-users.git,main`

**Comment by sergelogvinov** [comment]
Yep, it was in private repo. I've opened it.

It not necessary module, you can skip it.
I'll remove this module from example.

**Comment by mannp** [comment]
> Yep, it was in private repo. I've opened it.
> 
> It not necessary module, you can skip it. I'll remove this module from example.

Oh I see fair enough, thanks for the clarification.
