### ISSUE TITLE
Oracle VM does not boot.

### ISSUE THREAD

**Issue by jakoberpf** [sergelogvinov/terraform-talos#9]
## Report

Hey great project by the way. This is not straightly a bug report but I am hopping to get some info on how to get the Talos OS working on Oracle VMs. I found you terraform code to create a custom image from this issue https://github.com/siderolabs/talos/issues/9161 as I am also not able to get the boot working. I tried it with your code as well

```bash
wget https://github.com/siderolabs/talos/releases/download/v1.3.4/oracle-arm64.qcow2.xz
xz -d oracle-arm64.qcow2.xz
cp image_metadata_arm64.json image_metadata.json
tar zcf oracle-arm64.oci oracle-arm64.qcow2 image_metadata.json
tf init && tf plan && tf apply
```

to get the image and I can start some VMs (no with your terraform code, but my own) but their are not properly booting as it looks like, since I cannot ping or otherwise reach the VMs. Firewall rules are wide open for any tcp and udp traffic. Are there some special thing to keep in mind when using the image on a VM?

**Comment by sergelogvinov** [comment]
Hi, try tun control-plane first, it allows you to connect to the api without machine-config.
Probably you trying to use old version  (v1.3.4), 1.7.7 works perfect in my cluster.

in this folder https://github.com/sergelogvinov/terraform-talos/tree/main/oracle/images

```shell
make images-factory
make images-update
```

and instance runs like
https://github.com/sergelogvinov/terraform-talos/blob/main/oracle/instances-controlplane.tf#L20-L93

**Comment by jakoberpf** [comment]
Hey, thanks for the hint already. I tried multiple versions, from 1.3.4 over 1.6.7, 1.7.7 to 1.8.3 but I think its not the version but something I am missing in terms of configuration. I know from many other encounters that OCI is very picky with their network requirement. My instance resource looks now looks like 

```hcl
resource "oci_core_instance" "this" {
  compartment_id      = var.compartment_id
  availability_domain = var.availability_domain
  display_name        = local.name
  shape               = var.instance_shape

  shape_config {
    memory_in_gbs = var.instance_memory
    ocpus         = var.instance_ocpus
  }

  source_details {
    source_id               = var.instance_image != "default" ? var.instance_image : data.oci_core_images.this.images.0.id
    source_type             = "image"
    boot_volume_size_in_gbs = var.boot_volume_size_in_gbs
  }

  create_vnic_details {
    subnet_id              = var.subnet_id
    assign_public_ip       = true
    hostname_label         = local.name
    skip_source_dest_check = true
    nsg_ids = [
      oci_core_network_security_group.ping.id,
      oci_core_network_security_group.ssh.id,
      oci_core_network_security_group.extra.id
    ]
  }

  availability_config {
    is_live_migration_preferred = true
    recovery_action             = "RESTORE_INSTANCE"
  }

  launch_options {
    firmware                = "UEFI_64"
    boot_volume_type        = "PARAVIRTUALIZED"
    remote_data_volume_type = "PARAVIRTUALIZED"
    network_type            = "PARAVIRTUALIZED"
  }

  agent_config {
    are_all_plugins_disabled = true
    is_management_disabled   = true
    is_monitoring_disabled   = true
  }

  instance_options {
    are_legacy_imds_endpoints_disabled = true
  }

  metadata = {
    ssh_authorized_keys = join("\n", [var.ssh_public_key])
    user_data           = base64encode(var.machine_configuration)
  }

  lifecycle {
    # ignore_changes = [
    #   source_details
    # ]
    replace_triggered_by = [
      random_string.instance
    ]
  }
}
```

after taking most of the configuration from you. The machine-configuration you are building from the template is quite custom. Are there any specific fields that are required on OCI, like the `network` configuration ot the `sysctls`? I am generating the machine configuration with the `data "talos_machine_configuration"` resource and was hoping that i can extend it. I have a controlplane running in another cloud provider and want to add the support for some workers in OCI.

**Comment by sergelogvinov** [comment]
OCI has console, Can you check what happen on the screen?

Try regular OS and check internet and etc.

**Comment by jakoberpf** [comment]
If I use a ubuntu image it works fine, can login via console. But with the talos image via byoi, I am still trying to figure out whats the problem. I am only getting the UEFI shell. Was just hopping that you would remember something like this when you build you setup.

```txt
...
PEIM Loaded: ResetSystemPei.efi
PEIM Loaded: MemoryInit.efi
PEIM Loaded: PeiCore.efi
PEIM Loaded: PcdPeim.efi
PEIM Loaded: CpuPei.efi
UEFI Interactive Shell v2.2
EDK II
UEFI v2.70 (EDK II, 0x00010000)
```

When I do `map -r` I don't see any `fs0` so I think something is wrong with my image...

**Comment by jakoberpf** [comment]
For anyone after me having issues with this, looks like Apple Silicon or MacOS was the issue. Once I build the OCI package on a Linux x86 machine it works. @sergelogvinov Thanks for the support and figuring it out in the first place :-)
